In [124]:
import pandas as pd
import numpy as np

In [125]:
df=pd.read_csv(r"D:\NIT\DECEMBER\11 DEC  (SLR(SIMPLE))\11th - Regression model\SIMPLE LINEAR REGRESSION\Salary_Data.csv")

In [126]:
df

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

# mean

In [127]:
df.mean()

YearsExperience        5.313333
Salary             76003.000000
dtype: float64

In [128]:
df["Salary"].mean()

76003.0

# median

In [129]:
df.median() # this will give median of entire dataframe 


YearsExperience        4.7
Salary             65237.0
dtype: float64

In [130]:
df['Salary'].median() # this will give us median of that particular column 

65237.0

# Mode


In [131]:
df['Salary'].mode() # this will give us mode of that particular column 


0      37731
1      39343
2      39891
3      43525
4      46205
5      54445
6      55794
7      56642
8      56957
9      57081
10     57189
11     60150
12     61111
13     63218
14     64445
15     66029
16     67938
17     81363
18     83088
19     91738
20     93940
21     98273
22    101302
23    105582
24    109431
25    112635
26    113812
27    116969
28    121872
29    122391
Name: Salary, dtype: int64

# Variance


In [132]:
df.var() # this will give variance of entire dataframe 

YearsExperience    8.053609e+00
Salary             7.515510e+08
dtype: float64

In [133]:
df['Salary'].var() # this will give us variance of that particular column


751550960.4137931

# Standard deviation


In [134]:
df.std() # this will give standard deviation of entire dataframe 


YearsExperience        2.837888
Salary             27414.429785
dtype: float64

In [135]:
df['Salary'].std() # this will give us standard deviation of that particular column


27414.4297845823

# Correlation

In [136]:
df.corr() # this will give correlation of entire dataframe


YearsExperience    Salary
YearsExperience         1.000000  0.978242
Salary                  0.978242  1.000000

In [137]:
df['Salary'].corr(df['YearsExperience']) # this will give us correlation between these tw


0.9782416184887598

# Skewness

In [138]:
df.skew() # this will give skewness of entire dataframe 


YearsExperience    0.37956
Salary             0.35412
dtype: float64

In [139]:
df['Salary'].skew() # this will give us skewness of that particular column


0.35411967922959153

# Standard Error

In [140]:
df.sem() # this will give standard error of entire dataframe 

YearsExperience       0.518125
Salary             5005.167198
dtype: float64

In [141]:
df['Salary'].sem() # this will give us standard error of that particular column

5005.167198052405

# Coefficient of variation(cv)


In [142]:
# for calculating cv we have to import a library first
from scipy.stats import variation
variation(df.values) # this will give cv of entire dataframe 

array([0.5251297 , 0.35463929])

In [143]:
variation(df['Salary']) # this will give us cv of that particular column

0.3546392938275572

# Z-score

In [144]:
# for calculating Z-score we have to import a library first
import scipy.stats as stats
df.apply(stats.zscore) # this will give Z-score of entire dataframe

YearsExperience    Salary
0         -1.510053 -1.360113
1         -1.438373 -1.105527
2         -1.366693 -1.419919
3         -1.187494 -1.204957
4         -1.115814 -1.339781
5         -0.864935 -0.718307
6         -0.829096 -0.588158
7         -0.757416 -0.799817
8         -0.757416 -0.428810
9         -0.578216 -0.698013
10        -0.506537 -0.474333
11        -0.470697 -0.749769
12        -0.470697 -0.706620
13        -0.434857 -0.702020
14        -0.291498 -0.552504
15        -0.148138 -0.299217
16        -0.076458 -0.370043
17        -0.004779  0.262859
18         0.210261  0.198860
19         0.246100  0.665476
20         0.532819  0.583780
21         0.640339  0.826233
22         0.927058  0.938611
23         1.034577  1.402741
24         1.213777  1.240203
25         1.321296  1.097402
26         1.500496  1.519868
27         1.536336  1.359074
28         1.787215  1.721028
29         1.858894  1.701773

In [145]:
stats.zscore(df['Salary']) # this will give us Z-score of that particular column


0    -1.360113
1    -1.105527
2    -1.419919
3    -1.204957
4    -1.339781
5    -0.718307
6    -0.588158
7    -0.799817
8    -0.428810
9    -0.698013
10   -0.474333
11   -0.749769
12   -0.706620
13   -0.702020
14   -0.552504
15   -0.299217
16   -0.370043
17    0.262859
18    0.198860
19    0.665476
20    0.583780
21    0.826233
22    0.938611
23    1.402741
24    1.240203
25    1.097402
26    1.519868
27    1.359074
28    1.721028
29    1.701773
Name: Salary, dtype: float64

# Degree of Freedom

In [146]:
df.shape


(30, 2)

In [147]:
a = df.shape[0] # this will gives us no.of rows
b = df.shape[1] # this will give us no.of columns


In [148]:
print(a)
print(b)

30
2


In [149]:
degree_of_freedom = a-b
print(degree_of_freedom) # this will give us degree of freedom for entire dataset

28


# Sum of Squares Regression (SSR)

In [150]:
#First we have to separate dependent and independent variables
X=df.iloc[:,:-1].values #independent variable
y=df.iloc[:,1].values # dependent variable


In [151]:
print(X,y)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]] [ 39343  46205  37731  43525  39891  56642  60150  54445  64445  57189
  63218  55794  56957  57081  61111  67938  66029  83088  81363  93940
  91738  98273 101302 113812 109431 105582 116969 112635 122391 121872]


In [152]:
y_mean = np.mean(y) # this will calculate mean of dependent variable

In [153]:
y_mean

76003.0

In [154]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)

In [155]:
X_train,X_test,y_train,y_test

(array([[ 9.6],
        [ 4. ],
        [ 5.3],
        [ 7.9],
        [ 2.9],
        [ 5.1],
        [ 3.2],
        [ 4.5],
        [ 8.2],
        [ 6.8],
        [ 1.3],
        [10.5],
        [ 3. ],
        [ 2.2],
        [ 5.9],
        [ 6. ],
        [ 3.7],
        [ 3.2],
        [ 9. ],
        [ 2. ],
        [ 1.1],
        [ 7.1],
        [ 4.9],
        [ 4. ]]),
 array([[ 1.5],
        [10.3],
        [ 4.1],
        [ 3.9],
        [ 9.5],
        [ 8.7]]),
 array([112635,  55794,  83088, 101302,  56642,  66029,  64445,  61111,
        113812,  91738,  46205, 121872,  60150,  39891,  81363,  93940,
         57189,  54445, 105582,  43525,  39343,  98273,  67938,  56957],
       dtype=int64),
 array([ 37731, 122391,  57081,  63218, 116969, 109431], dtype=int64))

In [156]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,y_train)
y_predict = reg.predict(X_test) # before doing this we have to train,test and split our 

In [157]:
y_predict

array([ 40748.96184072, 122699.62295594,  64961.65717022,  63099.14214487,
       115249.56285456, 107799.50275317])

In [158]:
SSR = np.sum((y_predict-y_mean)**2)

In [159]:
SSR

6263152884.284127

# Sum of Squares Error (SSE)


In [160]:
#First we have to separate dependent and independent variables
X=df.iloc[:,:-1].values #independent variable
y=df.iloc[:,1].values # dependent variable


In [161]:
print(X,y)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]] [ 39343  46205  37731  43525  39891  56642  60150  54445  64445  57189
  63218  55794  56957  57081  61111  67938  66029  83088  81363  93940
  91738  98273 101302 113812 109431 105582 116969 112635 122391 121872]


In [162]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)

In [163]:
X_train,X_test,y_train,y_test

(array([[ 9.6],
        [ 4. ],
        [ 5.3],
        [ 7.9],
        [ 2.9],
        [ 5.1],
        [ 3.2],
        [ 4.5],
        [ 8.2],
        [ 6.8],
        [ 1.3],
        [10.5],
        [ 3. ],
        [ 2.2],
        [ 5.9],
        [ 6. ],
        [ 3.7],
        [ 3.2],
        [ 9. ],
        [ 2. ],
        [ 1.1],
        [ 7.1],
        [ 4.9],
        [ 4. ]]),
 array([[ 1.5],
        [10.3],
        [ 4.1],
        [ 3.9],
        [ 9.5],
        [ 8.7]]),
 array([112635,  55794,  83088, 101302,  56642,  66029,  64445,  61111,
        113812,  91738,  46205, 121872,  60150,  39891,  81363,  93940,
         57189,  54445, 105582,  43525,  39343,  98273,  67938,  56957],
       dtype=int64),
 array([ 37731, 122391,  57081,  63218, 116969, 109431], dtype=int64))

In [164]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,y_train)
y_predict = reg.predict(X_test) # before doing this we have to train,test and split our

In [165]:
y_predict 

array([ 40748.96184072, 122699.62295594,  64961.65717022,  63099.14214487,
       115249.56285456, 107799.50275317])

In [166]:
y = y[0:6]

In [167]:
y

array([39343, 46205, 37731, 43525, 39891, 56642], dtype=int64)

In [168]:
SSE = np.sum((y-y_predict)**2)
print(SSE)

15274062883.9432


# Sum of Squares Total (SST)


In [169]:
np.mean(df.values) 

38004.15666666666

In [170]:
mean_total = np.mean(df.values) # here df.to_numpy()will convert pandas Dataframe to Nump
SST = np.sum((df.values-mean_total)**2)
print(SST)

108429703765.82735


# R-Square


In [171]:
r_square = 1-(SSR/SST)
r_square

0.9422376648947554